name: Backend For Frontend Service CI

on:
  push:
    branches:
      - main
    paths:
      - "backend/nestjs/apps/bff-service/**"
      - "backend/nestjs/libs/**"
      - "backend/nestjs/package.json"
      - "backend/nestjs/package-lock.json"
      - ".github/workflows/bff-ci.yml"
  workflow_call:

jobs:
  build-and-push-docker-image:
    uses: ./.github/workflows/nestjs-ci-template.yml
    with:
      serviceName: 'bff'